name: waifspace
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  logger: 2.0.1
  sqflite: 2.3.0
  path: 1.8.3
  rss_dart: ^1.0.4
  adaptive_dialog: 1.9.0
  fluttertoast: 8.2.2
  jiffy: 6.2.1
  flutter_inappwebview: ^5.7.2+3
  timeago: 3.5.0
  intl: 0.18.1
  html: 0.15.4
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  http: 1.1.0
  get: 
    git: 
      url: https://github.com/jonataslaw/getx.git
      ref: master
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

