name: waifspace
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 图标库
  cupertino_icons: ^1.0.6

  # 日志处理
  logger: 2.0.2+1

  # sqlite 数据库
  sqflite: 2.3.0

  # 文件路径辅助库
  path: 1.8.3
  path_provider: ^2.1.1

  # rss 处理库
  rss_dart: ^1.0.4

  # 对话框
  adaptive_dialog: 1.9.0+2

  # 通知库
  fluttertoast: 8.2.2

  # 日期处理
  jiffy: 6.2.1
  timeago: 3.6.0

  # 浏览器
  flutter_inappwebview: 5.8.0

  # 多语言
  intl: 0.18.1

  # html 处理
  html: 0.15.4

  # 高性能数据库
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13

  # 网路请求
  dio: ^5.3.2
  talker_dio_logger: 2.3.1

  # 状态管理
  get: ^5.0.0-release-candidate-5

  visibility_detector: ^0.4.0+2

  # app分享按钮
  share_plus: 7.2.1

  # 左滑或者右划处理处理
  flutter_slidable: ^3.0.0

  # 可以缓存图片的image标签
  cached_network_image: ^3.3.0

  # 应用主题
  flex_color_scheme: ^7.3.1


dev_dependencies: 
  flutter_lints: 3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

