name: waifspace
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  # 图标库
  cupertino_icons: ^1.0.6

  # 日志处理
  logger: 2.0.2

  # sqlite 数据库
  sqflite: 2.3.0

  # 文件路径辅助库
  path: 1.8.3
  path_provider: ^2.1.1

  # rss 处理库
  rss_dart: ^1.0.4

  # 对话框
  adaptive_dialog: 1.9.0+2

  # 通知库
  fluttertoast: 8.2.2

  # 日期处理
  jiffy: 6.2.1
  timeago: 3.5.0

  # 浏览器
  flutter_inappwebview: ^5.7.2+3

  # 多语言
  intl: 0.18.1

  # html 处理
  html: 0.15.4

  # 高性能数据库
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13

  # 网路请求
  dio: ^5.3.2
  talker_dio_logger: ^2.3.0

  # 状态管理
  get: ^5.0.0-release-candidate-5

  # chatgpt 库
  dart_openai: ^4.0.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

