name: waifspace
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 图标库
  cupertino_icons: ^1.0.6

  # 程序调试日志处理
  logger: ^2.2.0

  # 应用日志显示
  talker_flutter: ^4.1.5

  # sqlite 数据库
  sqflite: ^2.3.3+1

  # 文件路径辅助库
  path: ^1.9.0
  path_provider: ^2.1.1

  # rss 处理库
  dart_rss: ^3.0.3

  # 对话框
  adaptive_dialog: ^2.1.0

  # 通知库
  toastification: ^2.0.0

  # 日期处理
  timeago: ^3.6.1

  # 浏览器
  flutter_inappwebview: ^6.0.0

  # 多语言
  intl: ^0.19.0

  # 网路请求
  dio: ^5.4.0
  talker_dio_logger: ^4.1.5

  # dio 网络重试
  dio_smart_retry: ^6.0.0

  # 状态管理
  get:
    git:
      url: https://github.com/jonataslaw/getx
      ref: master

  # 检测组件的可视性
  visibility_detector: ^0.4.0+2

  # app分享按钮
  share_plus: ^10.0.2

  # 左滑或者右划处理处理
  flutter_slidable: ^3.0.0

  # 可以缓存图片的image标签
  cached_network_image: ^3.4.1

  # 应用主题
  flex_color_scheme: ^7.3.1

  # 应用图标
  font_awesome_flutter: ^10.6.0

  # 下载管理
  flutter_downloader: ^1.11.6

  # svg 图片显示
  flutter_svg: ^2.0.9

  # html 解析和处理，用于去掉 css 和 js
  html: ^0.15.4

  # 用于文字的 "更多" 显示
  readmore: ^3.0.0

  # 文件选择
  file_picker: ^8.1.2

  # 权限处理
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/javascripts/
  uses-material-design: true

