name: waifspace
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get:
    git:
      url: https://github.com/jonataslaw/getx.git
      ref: master
  logger: 2.0.1
  sqflite: 2.3.0
  path: 1.8.3
  path_provider: 2.1.0
  dart_rss: 3.0.1
  adaptive_dialog: 1.9.0
  fluttertoast: 8.2.2
  jiffy: 6.2.1
  flutter_inappwebview: ^5.7.2+3
  timeago: 3.5.0
  intl: 0.18.1
  html: 0.15.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

